export const MANAGED_HOOK_SCRIPT_CHUNK_3 = JSON.parse(
  [
    '"        resolution.preset,\\n        input,\\n        [],\\n      );\\n    }\\n\\n    return null;\\n  }\\n\\n  const ',
    "maxTurns = getMaxTurns(preset);\\n  if (maxTurns === null) {\\n    clearRemainingTurns(db, sessionId);\\n    clea",
    "rSessionAwaitingReplies(db, sessionId);\\n    return null;\\n  }\\n\\n  const remainingTurns = getRemainingTurns(d",
    "b, sessionId) ?? maxTurns;\\n  if (remainingTurns <= 0) {\\n    clearSessionAwaitingReplies(db, sessionId);\\n   ",
    " return null;\\n  }\\n\\n  setRemainingTurns(db, sessionId, remainingTurns - 1);\\n  clearSessionAwaitingReplies(d",
    "b, sessionId);\\n  const remotePrompt =\\n    readPersistentSessionRemotePrompt(db, sessionId) ?? consumeSession",
    'RemotePrompt(db, sessionId);\\n  return {\\n    decision: \\"block\\",\\n    reason: remotePrompt ?? renderPrompt(s',
    "ettingsRow.default_prompt, remainingTurns - 1),\\n    remainingTurnsBefore: remainingTurns,\\n    remainingTurns",
    'After: remainingTurns - 1,\\n    promptSource: remotePrompt ? \\"telegram\\" : \\"default\\",\\n  };\\n}\\n\\n',
    "async function sendStopNotifications(db, input) {\\n  if",
    ' (input.hook_event_name !== \\"Stop\\") {\\n    return [];\\n  }\\n\\n  const message =\\n    typeof input.last_assis',
    'tant_message === \\"string\\" ? input.last_assistant_message.trim() : \\"\\";\\n  if (message.length === 0) {\\n    ',
    "return [];\\n  }\\n\\n  const selectedNotifications = db\\n    .query(\\n      `select\\n        n.id,\\n        n.la",
    "bel,\\n        n.channel,\\n        n.webhook_url,\\n        n.chat_id,\\n        n.bot_token,\\n        n.bot_url,",
    "\\n        n.created_at\\n      from notifications n\\n      inner join session_notifications sn on sn.notificati",
    "on_id = n.id\\n      where sn.session_id = ?\\n      order by n.created_at asc, n.id asc`,\\n    )\\n    .all(inpu",
    "t.session_id);\\n  if (selectedNotifications.length === 0) {\\n    return [];\\n  }\\n\\n  const sessionRow = db\\n ",
    '   .query(\\"select session_ref, title, archived, cwd from sessions where session_id = ?\\")\\n    .get(input.ses',
    "sion_id);\\n  if (Boolean(sessionRow?.archived)) {\\n    return [];\\n  }\\n  const effectivePreset = getEffectiveP",
    "reset(db, input.session_id);\\n  const telegramTexts = buildTelegramNotificationChunks({\\n    cwd: sessionRow?.c",
    "wd ?? null,\\n    sessionRef: sessionRow?.session_ref ?? null,\\n    sessionTitle: sessionRow?.title ?? null,\\n ",
    "   message,\\n    preset: effectivePreset,\\n    telegramNotificationFooter,\\n    maxLength: telegramMaxMessageLe",
    "ngth,\\n  });\\n\\n  const deliveredTelegramTargets = [];\\n  const results = await Promise.allSettled(\\n    select",
    'edNotifications.map(async (notification) => {\\n      if (notification.channel === \\"slack\\") {\\n        const ',
    "response = await fetch(notification.w",
    'ebhook_url, {\\n          method: \\"POST\\",\\n          headers: {\\n            \\"content-type\\": \\"application/',
    'json\\",\\n          },\\n          body: JSON.stringify({ text: message }),\\n        });\\n        if (!response.',
    "ok) {\\n          throw new Error(`Slack notification failed with status ${response.status}`);\\n        }\\n    ",
    '    return;\\n      }\\n\\n      const telegramEndpoint =\\n        (typeof notification.bot_token === \\"string\\" ',
    "&& notification.bot_token.length > 0\\n          ? buildTelegramBotUrl(notification.bot_token)\\n          : not",
    'ification.bot_url) ?? null;\\n      if (!telegramEndpoint) {\\n        throw new Error(\\"Telegram notification i',
    's missing a bot token.\\");\\n      }\\n\\n      for (const telegramText of telegramTexts) {\\n        const respon',
    'se = await fetch(telegramEndpoint, {\\n          method: \\"POST\\",\\n          headers: {\\n            \\"content',
    '-type\\": \\"application/x-www-form-urlencoded;charset=UTF-8\\",\\n          },\\n          body: new URLSearchPara',
    "ms({\\n            chat_id: notification.chat_id,\\n            text: telegramText,\\n          }).toString(),\\n ",
    "       });\\n        if (!response.ok) {\\n          throw new Error(`Telegram notification failed with status $",
    "{response.status}`);\\n        }\\n\\n        const payload = await response.json();\\n        if (!payload?.ok ||",
    ' typeof payload?.result?.message_id !== \\"number\\") {\\n          throw new Error(payload?.description || \\"Tel',
    'egram notification did not return a message id.\\");\\n        }\\n\\n        db.query(\\n          `insert into te',
    "legram_delivery_receipts (\\n            id,\\n            notification_id,\\n            session_id,\\n          ",
    "  bot_token,\\n            chat_id,\\n            telegram_message_id,\\n            created_at\\n          ) valu",
    "es (?, ?, ?, ?, ?, ?, ?)`,\\n        ).run(\\n          crypto.randomUUID(),\\n          notification.id,\\n      ",
    '    input.session_id,\\n          typeof notification.bot_token === \\"string\\" ? notification.bot_token : \\"\\",',
    "\\n          notification.chat_id,\\n          payload.result.message_id,\\n          nowIsoString(),\\n        );",
    '\\n      }\\n\\n      deliveredTelegramTargets.push({\\n        botToken: typeof notification.bot_token === \\"stri',
    'ng\\" ? notification.bot_token : \\"\\",\\n        chatId: notification.chat_id,\\n      });\\n    }),\\n  );\\n\\n  co',
    'nst failures = results.flatMap((result, index) =>\\n    result.status === \\"rejected\\"\\n      ? [\\n          {\\',
    "n            notificationId: selectedNotifications[index]?.id ?? null,\\n            channel: selectedNotificat",
    "ions[index]?.channel ?? null,\\n            error: result.reason instanceof Error ? result.reason.message : Str",
    'ing(result.reason),\\n          },\\n        ]\\n      : [],\\n  );\\n\\n  await appendHookDebugLog({\\n    type: \\"n',
    'otification\\",\\n    hookEventName: \\"Stop\\",\\n    sessionId: input.session_id,\\n    deliveredCount: results.le',
    "ngth - failures.length,\\n    failedCount: failures.length,\\n    failures,\\n  });\\n\\n  return deliveredTelegram",
    "Targets;\\n}\\n\\nfunction getTelegramChatDisplayName(chat: {\\n  title?: string | null;\\n  first_name?: string | ",
    "null;\\n  last_name?: string | null;\\n  username?: string | null;\\n}) {\\n  const nameParts = [chat.first_name, ",
    'chat.last_name].filter(\\n    (part): part is string => typeof part === \\"string\\" && part.trim().length > 0,\\n',
    '  );\\n\\n  if (nameParts.length > 0) {\\n    return nameParts.join(\\" \\");\\n  }\\n\\n  if (typeof chat.title === \\',
    '"string\\" && chat.title.trim().length > 0) {\\n    return chat.title.trim();\\n  }\\n\\n  if (typeof chat.username',
    ' === \\"string\\" && chat.username.trim().length > 0) {\\n    return `@${chat.username.trim()}`;\\n  }\\n\\n  return',
    ' \\"Unknown chat\\";\\n}\\n\\nasync function main() {\\n  const input = JSON.parse(await Bun.stdin.text());\\n  const',
    ' hookEventName = input.hook_event_name;\\n\\n  if (\\n    hookEventName !== \\"SessionStart\\" &&\\n    hookEventNam',
    'e !== \\"Stop\\" &&\\n    hookEventName !== \\"UserPromptSubmit\\"\\n  ) {\\n    return;\\n  }\\n\\n  await ensureDirect',
    "ory(dirname(databasePath));\\n  const db = new Database(databasePath, { create: true });\\n  configureDatabase(d",
    'b);\\n  applyMigrations(db);\\n\\n  const sessionCountBefore = db.query(\\"select count(*) as count from sessions\\',
    '").get().count;\\n\\n  if (typeof input.session_id !== \\"string\\" || input.session_id.length === 0) {\\n    await',
    ' appendHookDebugLog({\\n      type: \\"hook-event\\",\\n      hookEventName,\\n      action: \\"ignored\\",\\n      re',
    'ason: \\"missing-session-id\\",\\n      payload: input,\\n      sessionCountBefore,\\n      sessionCountAfter: sess',
    "ionCountBefore,\\n    });\\n    return;\\n  }\\n\\n  const runtimeState = getLoopndrollRuntimeState(db);\\n  if (runt",
    'imeState !== \\"running\\") {\\n    await appendHookDebugLog({\\n      type: \\"hook-event\\",\\n      hookEventName',
    ',\\n      action: \\"ignored\\",\\n      reason: `runtime-${runtimeState}`,\\n      sessionId: input.session_id,\\n ',
    "     payload: input,\\n      sessionCountBefore,\\n      sessionCountAfter: sessionCountBefore,\\n    });\\n    re",
    'turn;\\n  }\\n\\n  if (hookEventName === \\"SessionStart\\") {\\n    const session =',
    ' upsertSession(db, input, input.source === \\"resume\\" ? \\"resume\\" : \\"startup\\");\\n    const sessionCountAfte',
    'r = db.query(\\"select count(*) as count from sessions\\").get().count;\\n    await appendHookDebugLog({\\n      t',
    'ype: \\"hook-event\\",\\n      hookEventName,\\n      action: \\"upsert-session\\",\\n      sessionId: input.session_',
    "id,\\n      payload: input,\\n      sessionCountBefore,\\n      sessionCountAfter,\\n      storedSession: session,",
    '\\n    });\\n    return;\\n  }\\n\\n  if (hookEventName === \\"UserPromptSubmit\\") {\\n    const existingSession = ge',
    'tSession(db, input.session_id);\\n    const session = upsertSession(db, input, existingSession?.source ?? \\"sta',
    'rtup\\");\\n    const sessionCountAfter = db.query(\\"select count(*) as count from sessions\\").get().count;\\n   ',
    ' await appendHookDebugLog({\\n      type: \\"hook-event\\",\\n      hookEventName,\\n      action: existingSession ',
    '? \\"update-session-title\\" : \\"recover-session-on-prompt\\",\\n      sessionId: input.session_id,\\n      payload',
    ": input,\\n      sessionCountBefore,\\n      sessionCountAfter,\\n      storedSession: session,\\n    });\\n    ret",
    "urn;\\n  }\\n\\n  const settingsRow = getSettings(db);\\n  const existingSession = getSession(db, input.session_id",
    ");\\n  const generatedTitle =\\n    input.transcript_path == null ? parseGeneratedTitlePayload(input.last_assist",
    "ant_message) : null;\\n  const titleTargetSession = generatedTitle ? findGeneratedTitleTargetSession(db, input)",
    " : null;\\n\\n  if (generatedTitle && titleTargetSession) {\\n    updateSessionTitle(db, titleTargetSession.sessi",
    'onId, generatedTitle);\\n    const sessionCountAfter = db.query(\\"select count(*) as count from sessions\\").get',
    '().count;\\n    await appendHookDebugLog({\\n      type: \\"hook-event\\",\\n      hookEventName,\\n      action: \\"',
    'apply-generated-title\\",\\n      sessionId: input.session_id,\\n      targetSessionId: titleTargetSession.sessio',
    "nId,\\n      generatedTitle,\\n      payload: input,\\n      sessionCountBefore,\\n      sessionCountAfter,\\n    }",
    ');\\n    return;\\n  }\\n\\n  if (existingSession?.archived) {\\n    const session = upsertSession(db, input, \\"sto',
    'p\\");\\n    writeSession(db, session, true);\\n    const sessionCountAfter = db.query(\\"select count(*) as count',
    ' from sessions\\").get().count;\\n    await appendHookDebugLog({\\n      type: \\"hook-event\\",\\n      hookEventNa',
    'me,\\n      action: \\"ignored\\",\\n      reason: \\"archived-session\\",\\n      sessionId: input.session_id,\\n    ',
    "  payload: input,\\n      sessionCountBefore,\\n      sessionCountAfter,\\n      storedSession: session,\\n    });",
    '\\n    return;\\n  }\\n\\n  const session = upsertSession(db, input, \\"stop\\");\\n  session.stopCount += 1;\\n  writ',
    "eSession(db, session, true);\\n  const deliveredTelegramTargets = await sendStopNotifications(db, input);\\n\\n  ",
    "const preset = getEffectivePreset(db, input.session_id);\\n  const stopDecision = await applyStopDecision(\\n   ",
    " db,\\n    settingsRow,\\n    input.session_id,\\n    preset,\\n    input,\\n    deliveredTelegramTargets,\\n  );\\n ",
    ' const sessionCountAfter = db.query(\\"select count(*) as count from sessions\\").get().count;\\n  await appendHo',
    'okDebugLog({\\n    type: \\"hook-event\\",\\n    hookEventName,\\n    action: stopDecision ? \\"block-stop\\" : \\"all',
    'ow-stop\\",\\n    reason: existingSession ? undefined : \\"recover-session-on-stop\\",\\n    sessionId: input.sessi',
    "on_id,\\n    payload: input,\\n    sessionCountBefore,\\n    sessionCountAfter,\\n    storedSession: session,\\n   ",
    " preset,\\n    remainingTurnsBefore: stopDecision?.remainingTurnsBefore ?? null,\\n    remainingTurnsAfter: stop",
    "Decision?.remainingTurnsAfter ?? null,\\n    promptSource: stopDecision?.promptSource ?? null,\\n  });\\n\\n  if (",
    "stopDecision) {\\n    const hookOutput = toHookStopOutput(stopDecision);\\n    if (hookOutput) {\\n      process.",
    "stdout.write(`${JSON.stringify(hookOutput)}\\\\n`);\\n    }\\n  }\\n}\\n\\nawait main().catch(async (error) => {\\n  a",
    'wait appendHookDebugLog({\\n    type: \\"hook-event\\",\\n    action: \\"uncaught-error\\",\\n    message: error inst',
    "anceof Error ? error.message : String(error),\\n    stack: error instanceof Error ? error.stack : null,\\n  });\\",
    'n  throw error;\\n});\\n"',
  ].join(""),
);
